# Generated by Django 5.1.4 on 2024-12-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiras.financeira')),
            ],
        ),
    ]
